### ISSUE TITLE
Alamofire dependency

### ISSUE THREAD

**Issue by MaheshSC** [BitBurst-GmbH/bitlabs-ios-sdk#26]
It is not a good practise when you are build library with having dependency on other libraries like Alamofire

Now My project am using lower version of Alamofire 
Because of your SDK how can I upgrade my entire project 
It is better remove the Alamofire and upload new version ASAP

**Comment by omaRaad** [comment]
@MaheshSC What version of Alamofire do you use?

**Comment by MaheshSC** [comment]
@omaRaad  We are using Alamofire  v 4.9.1

**Comment by omaRaad** [comment]
@MaheshSC 
Since April 2024, a Privacy Manifest must be included for certain SDKs that are used in any app submitted to the App Store. 

Alamofire is one of those SDKs. That's why we had to update it to the version where it was added, which is v5.9.0
